[package]
name = "elrs-rainbow-table"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

default-run = "elrs-rainbow-table"

[features]
time-lookup = []

[dependencies]
anyhow = "1.0.75"
axum = { version = "0.6.20", features = ["http2", "json", "macros"] }
bytesize = "1.3.0"
md-5 = { version = "0.10.5", features = ["asm"] }
memchr = "2.5.0"
rayon = "1.7.0"
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
ureq = "2.7.1"

[profile.release]
lto = "thin"
strip = true
