[package]
name = "elrs-rainbow-table"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[features]
time-lookup = []

[dependencies]
bytesize = "1.3.0"
md-5 = { version = "0.10.5", features = ["asm"] }
memchr = "2.5.0"
rayon = "1.7.0"

[profile.release]
lto = "thin"
strip = true
